export const ACTION_OPENINBROWSER = 'ACTION_OPENINBROWSER';
export const ACTION_SHARE = 'ACTION_SHARE';
export const ACTION_COPY = 'ACTION_COPY';
export const ACTION_MENTION = 'ACTION_MENTION';
export const ACTION_HIDE = 'ACTION_HIDE';