export const SET_BACKGROUNDIMAGE = "SET_BACKGROUNDIMAGE";
export const DELETE_BACKGROUNDIMAGE = "DELETE_BACKGROUNDIMAGE";

export const INVISIBLE_SETTING = "INVISIBLE_SETTING";

export const CHANGE_FONTSIZE = "CHANGE_FONTSIZE";

export const CHANGE_THEME = "CHANGE_THEME";

export const CONFIG_LOAD = "CONFIG_LOAD";

export const CONFIG_RESET = "CONFIG_RESET";
