export const SET_BACKGROUNDIMAGE = "SET_BACKGROUNDIMAGE";
export const DELETE_BACKGROUNDIMAGE = "DELETE_BACKGROUNDIMAGE";

export const INVISIBLE_SETTING = "VISIBLE_HOME";

export const CONFIG_LOAD = "CONFIG_LOAD";

export const CONFIG_RESET = "CONFIG_RESET";