export const SET_BACKGROUNDIMAGE = "SET_BACKGROUNDIMAGE";
export const DELETE_BACKGROUNDIMAGE = "DELETE_BACKGROUNDIMAGE";

export const INVISIBLE_SETTING = "INVISIBLE_SETTING";

export const SMART_MODE = "SMART_MODE";
export const TIMELINE_PERFORM = "TIMELINE_PERFORM";

export const CONFIG_LOAD = "CONFIG_LOAD";

export const CONFIG_RESET = "CONFIG_RESET";
