export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const DELETED_CURRENT_USER = "DELETED_CURRENT_USER";
export const NOTIFICATION_PUSH = "NOTIFICATION_PUSH";
export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";
