export const NEW_UPDATE_MASTOLIST = "NEW_UPDATE_MASTOLIST";
export const OLD_UPDATE_MASTOLIST = "OLD_UPDATE_MASTOLIST";
export const REFRESHING_MASTOLIST = "REFRESHING_MASTOLIST";
export const ALLCLEAR_MASTOLIST = "ALLCLEAR_MASTOLIST";