export const NEW_UPDATE_MASTOLIST = "NEW_UPDATE_MASTOLIST";
export const OLD_UPDATE_MASTOLIST = "OLD_UPDATE_MASTOLIST";
export const REFRESHING_MASTOLIST = "REFRESHING_MASTOLIST";
export const STOP_REFRESHING_MASTOLIST = "STOP_REFRESHING_MASTOLIST";
export const ALLCLEAR_MASTOLIST = "ALLCLEAR_MASTOLIST";
export const GETLOCALDATA_MASTOLIST = "GETLOCALDATA_MASTOLIST";
export const HIDE_MASTOLIST = "HIDE_MASTOLIST";
