export const BOOST_MASTOROW = "BOOST_MASTOROW";
export const FAVOURITE_MASTOROW = "FAVOURITE_MASTOROW";
export const BOOKMARK_MASTOROW = "BOOKMARK_MASTOROW";
export const FOLLOW_MASTOROW = "FOLLOW_MASTOROW";