export const PUSHNOTIFICATION_RESET = "PUSHNOTIFICATION_RESET";
export const PUSHNOTIFICATION_LOAD = "PUSHNOTIFICATION_LOAD";
export const PUSHNOTIFICATION_SUBSCRIBE = "PUSHNOTIFICATION_SUBSCRIBE";
export const PUSHNOTIFICATION_UNSUBSCRIBE = "PUSHNOTIFICATION_UNSUBSCRIBE";